#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOLService
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DemoDVD")]
	public partial class DBContextDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertImgLink(ImgLink instance);
    partial void UpdateImgLink(ImgLink instance);
    partial void DeleteImgLink(ImgLink instance);
    partial void InsertVietlottVN(VietlottVN instance);
    partial void UpdateVietlottVN(VietlottVN instance);
    partial void DeleteVietlottVN(VietlottVN instance);
    #endregion
		
		public DBContextDataContext() : 
				base(global::BOLService.Properties.Settings.Default.DemoDVDConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBContextDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBContextDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBContextDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBContextDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ImgLink> ImgLinks
		{
			get
			{
				return this.GetTable<ImgLink>();
			}
		}
		
		public System.Data.Linq.Table<VietlottVN> VietlottVNs
		{
			get
			{
				return this.GetTable<VietlottVN>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetRandomImage")]
		public ISingleResult<GetRandomImageResult> GetRandomImage([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> randomOn, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> amountReturn)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), randomOn, amountReturn);
			return ((ISingleResult<GetRandomImageResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetListImgByDomain")]
		public ISingleResult<GetListImgByDomainResult> GetListImgByDomain([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DomainName", DbType="NVarChar(500)")] string domainName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageIndex", DbType="Int")] System.Nullable<int> pageIndex, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageSize", DbType="Int")] System.Nullable<int> pageSize, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TotalRecords", DbType="Int")] ref System.Nullable<int> totalRecords)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), domainName, pageIndex, pageSize, totalRecords);
			totalRecords = ((System.Nullable<int>)(result.GetParameterValue(3)));
			return ((ISingleResult<GetListImgByDomainResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetRandomImageByCondition")]
		public ISingleResult<GetRandomImageByConditionResult> GetRandomImageByCondition([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsNice", DbType="Int")] System.Nullable<int> isNice, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HotLeve", DbType="Int")] System.Nullable<int> hotLeve, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Domain", DbType="NVarChar(1000)")] string domain, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> amountReturn)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), isNice, hotLeve, domain, amountReturn);
			return ((ISingleResult<GetRandomImageByConditionResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ImgLink")]
	public partial class ImgLink : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _linkimg;
		
		private System.DateTime _CreateDate;
		
		private System.Nullable<bool> _IsDownLoaded;
		
		private string _Domain;
		
		private string _Counter;
		
		private string _GroupName;
		
		private string _Category;
		
		private System.Nullable<bool> _IsBadURL;
		
		private System.Nullable<bool> _IsCheckLive;
		
		private System.Nullable<int> _HotLevel;
		
		private System.Nullable<bool> _IsNice;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnlinkimgChanging(string value);
    partial void OnlinkimgChanged();
    partial void OnCreateDateChanging(System.DateTime value);
    partial void OnCreateDateChanged();
    partial void OnIsDownLoadedChanging(System.Nullable<bool> value);
    partial void OnIsDownLoadedChanged();
    partial void OnDomainChanging(string value);
    partial void OnDomainChanged();
    partial void OnCounterChanging(string value);
    partial void OnCounterChanged();
    partial void OnGroupNameChanging(string value);
    partial void OnGroupNameChanged();
    partial void OnCategoryChanging(string value);
    partial void OnCategoryChanged();
    partial void OnIsBadURLChanging(System.Nullable<bool> value);
    partial void OnIsBadURLChanged();
    partial void OnIsCheckLiveChanging(System.Nullable<bool> value);
    partial void OnIsCheckLiveChanged();
    partial void OnHotLevelChanging(System.Nullable<int> value);
    partial void OnHotLevelChanged();
    partial void OnIsNiceChanging(System.Nullable<bool> value);
    partial void OnIsNiceChanged();
    #endregion
		
		public ImgLink()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_linkimg", DbType="NVarChar(2500) NOT NULL", CanBeNull=false)]
		public string linkimg
		{
			get
			{
				return this._linkimg;
			}
			set
			{
				if ((this._linkimg != value))
				{
					this.OnlinkimgChanging(value);
					this.SendPropertyChanging();
					this._linkimg = value;
					this.SendPropertyChanged("linkimg");
					this.OnlinkimgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime NOT NULL")]
		public System.DateTime CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDownLoaded", DbType="Bit")]
		public System.Nullable<bool> IsDownLoaded
		{
			get
			{
				return this._IsDownLoaded;
			}
			set
			{
				if ((this._IsDownLoaded != value))
				{
					this.OnIsDownLoadedChanging(value);
					this.SendPropertyChanging();
					this._IsDownLoaded = value;
					this.SendPropertyChanged("IsDownLoaded");
					this.OnIsDownLoadedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Domain", DbType="NVarChar(1000)")]
		public string Domain
		{
			get
			{
				return this._Domain;
			}
			set
			{
				if ((this._Domain != value))
				{
					this.OnDomainChanging(value);
					this.SendPropertyChanging();
					this._Domain = value;
					this.SendPropertyChanged("Domain");
					this.OnDomainChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Counter", DbType="NVarChar(500)")]
		public string Counter
		{
			get
			{
				return this._Counter;
			}
			set
			{
				if ((this._Counter != value))
				{
					this.OnCounterChanging(value);
					this.SendPropertyChanging();
					this._Counter = value;
					this.SendPropertyChanged("Counter");
					this.OnCounterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupName", DbType="NVarChar(1000)")]
		public string GroupName
		{
			get
			{
				return this._GroupName;
			}
			set
			{
				if ((this._GroupName != value))
				{
					this.OnGroupNameChanging(value);
					this.SendPropertyChanging();
					this._GroupName = value;
					this.SendPropertyChanged("GroupName");
					this.OnGroupNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category", DbType="NVarChar(1000)")]
		public string Category
		{
			get
			{
				return this._Category;
			}
			set
			{
				if ((this._Category != value))
				{
					this.OnCategoryChanging(value);
					this.SendPropertyChanging();
					this._Category = value;
					this.SendPropertyChanged("Category");
					this.OnCategoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsBadURL", DbType="Bit")]
		public System.Nullable<bool> IsBadURL
		{
			get
			{
				return this._IsBadURL;
			}
			set
			{
				if ((this._IsBadURL != value))
				{
					this.OnIsBadURLChanging(value);
					this.SendPropertyChanging();
					this._IsBadURL = value;
					this.SendPropertyChanged("IsBadURL");
					this.OnIsBadURLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsCheckLive", DbType="Bit")]
		public System.Nullable<bool> IsCheckLive
		{
			get
			{
				return this._IsCheckLive;
			}
			set
			{
				if ((this._IsCheckLive != value))
				{
					this.OnIsCheckLiveChanging(value);
					this.SendPropertyChanging();
					this._IsCheckLive = value;
					this.SendPropertyChanged("IsCheckLive");
					this.OnIsCheckLiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HotLevel", DbType="Int")]
		public System.Nullable<int> HotLevel
		{
			get
			{
				return this._HotLevel;
			}
			set
			{
				if ((this._HotLevel != value))
				{
					this.OnHotLevelChanging(value);
					this.SendPropertyChanging();
					this._HotLevel = value;
					this.SendPropertyChanged("HotLevel");
					this.OnHotLevelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsNice", DbType="Bit")]
		public System.Nullable<bool> IsNice
		{
			get
			{
				return this._IsNice;
			}
			set
			{
				if ((this._IsNice != value))
				{
					this.OnIsNiceChanging(value);
					this.SendPropertyChanging();
					this._IsNice = value;
					this.SendPropertyChanged("IsNice");
					this.OnIsNiceChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VietlottVN")]
	public partial class VietlottVN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _VietLottID;
		
		private int _DrawId;
		
		private System.DateTime _DayPrize;
		
		private string _FullBlockNumber;
		
		private int _NumberOne;
		
		private int _NumberTwo;
		
		private int _NumberThree;
		
		private int _NumberFour;
		
		private int _NumberFive;
		
		private int _NumberSix;
		
		private System.DateTime _ImportDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnVietLottIDChanging(int value);
    partial void OnVietLottIDChanged();
    partial void OnDrawIdChanging(int value);
    partial void OnDrawIdChanged();
    partial void OnDayPrizeChanging(System.DateTime value);
    partial void OnDayPrizeChanged();
    partial void OnFullBlockNumberChanging(string value);
    partial void OnFullBlockNumberChanged();
    partial void OnNumberOneChanging(int value);
    partial void OnNumberOneChanged();
    partial void OnNumberTwoChanging(int value);
    partial void OnNumberTwoChanged();
    partial void OnNumberThreeChanging(int value);
    partial void OnNumberThreeChanged();
    partial void OnNumberFourChanging(int value);
    partial void OnNumberFourChanged();
    partial void OnNumberFiveChanging(int value);
    partial void OnNumberFiveChanged();
    partial void OnNumberSixChanging(int value);
    partial void OnNumberSixChanged();
    partial void OnImportDateChanging(System.DateTime value);
    partial void OnImportDateChanged();
    #endregion
		
		public VietlottVN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VietLottID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int VietLottID
		{
			get
			{
				return this._VietLottID;
			}
			set
			{
				if ((this._VietLottID != value))
				{
					this.OnVietLottIDChanging(value);
					this.SendPropertyChanging();
					this._VietLottID = value;
					this.SendPropertyChanged("VietLottID");
					this.OnVietLottIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DrawId", DbType="Int NOT NULL")]
		public int DrawId
		{
			get
			{
				return this._DrawId;
			}
			set
			{
				if ((this._DrawId != value))
				{
					this.OnDrawIdChanging(value);
					this.SendPropertyChanging();
					this._DrawId = value;
					this.SendPropertyChanged("DrawId");
					this.OnDrawIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DayPrize", DbType="DateTime NOT NULL")]
		public System.DateTime DayPrize
		{
			get
			{
				return this._DayPrize;
			}
			set
			{
				if ((this._DayPrize != value))
				{
					this.OnDayPrizeChanging(value);
					this.SendPropertyChanging();
					this._DayPrize = value;
					this.SendPropertyChanged("DayPrize");
					this.OnDayPrizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullBlockNumber", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string FullBlockNumber
		{
			get
			{
				return this._FullBlockNumber;
			}
			set
			{
				if ((this._FullBlockNumber != value))
				{
					this.OnFullBlockNumberChanging(value);
					this.SendPropertyChanging();
					this._FullBlockNumber = value;
					this.SendPropertyChanged("FullBlockNumber");
					this.OnFullBlockNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumberOne", DbType="Int NOT NULL")]
		public int NumberOne
		{
			get
			{
				return this._NumberOne;
			}
			set
			{
				if ((this._NumberOne != value))
				{
					this.OnNumberOneChanging(value);
					this.SendPropertyChanging();
					this._NumberOne = value;
					this.SendPropertyChanged("NumberOne");
					this.OnNumberOneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumberTwo", DbType="Int NOT NULL")]
		public int NumberTwo
		{
			get
			{
				return this._NumberTwo;
			}
			set
			{
				if ((this._NumberTwo != value))
				{
					this.OnNumberTwoChanging(value);
					this.SendPropertyChanging();
					this._NumberTwo = value;
					this.SendPropertyChanged("NumberTwo");
					this.OnNumberTwoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumberThree", DbType="Int NOT NULL")]
		public int NumberThree
		{
			get
			{
				return this._NumberThree;
			}
			set
			{
				if ((this._NumberThree != value))
				{
					this.OnNumberThreeChanging(value);
					this.SendPropertyChanging();
					this._NumberThree = value;
					this.SendPropertyChanged("NumberThree");
					this.OnNumberThreeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumberFour", DbType="Int NOT NULL")]
		public int NumberFour
		{
			get
			{
				return this._NumberFour;
			}
			set
			{
				if ((this._NumberFour != value))
				{
					this.OnNumberFourChanging(value);
					this.SendPropertyChanging();
					this._NumberFour = value;
					this.SendPropertyChanged("NumberFour");
					this.OnNumberFourChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumberFive", DbType="Int NOT NULL")]
		public int NumberFive
		{
			get
			{
				return this._NumberFive;
			}
			set
			{
				if ((this._NumberFive != value))
				{
					this.OnNumberFiveChanging(value);
					this.SendPropertyChanging();
					this._NumberFive = value;
					this.SendPropertyChanged("NumberFive");
					this.OnNumberFiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumberSix", DbType="Int NOT NULL")]
		public int NumberSix
		{
			get
			{
				return this._NumberSix;
			}
			set
			{
				if ((this._NumberSix != value))
				{
					this.OnNumberSixChanging(value);
					this.SendPropertyChanging();
					this._NumberSix = value;
					this.SendPropertyChanged("NumberSix");
					this.OnNumberSixChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImportDate", DbType="DateTime NOT NULL")]
		public System.DateTime ImportDate
		{
			get
			{
				return this._ImportDate;
			}
			set
			{
				if ((this._ImportDate != value))
				{
					this.OnImportDateChanging(value);
					this.SendPropertyChanging();
					this._ImportDate = value;
					this.SendPropertyChanged("ImportDate");
					this.OnImportDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class GetRandomImageResult
	{
		
		private int _ID;
		
		private string _linkimg;
		
		private System.DateTime _CreateDate;
		
		public GetRandomImageResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_linkimg", DbType="NVarChar(2500) NOT NULL", CanBeNull=false)]
		public string linkimg
		{
			get
			{
				return this._linkimg;
			}
			set
			{
				if ((this._linkimg != value))
				{
					this._linkimg = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime NOT NULL")]
		public System.DateTime CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this._CreateDate = value;
				}
			}
		}
	}
	
	public partial class GetListImgByDomainResult
	{
		
		private int _Id;
		
		private int _ImgID;
		
		private string _ImgLink;
		
		public GetListImgByDomainResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImgID", DbType="Int NOT NULL")]
		public int ImgID
		{
			get
			{
				return this._ImgID;
			}
			set
			{
				if ((this._ImgID != value))
				{
					this._ImgID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImgLink", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string ImgLink
		{
			get
			{
				return this._ImgLink;
			}
			set
			{
				if ((this._ImgLink != value))
				{
					this._ImgLink = value;
				}
			}
		}
	}
	
	public partial class GetRandomImageByConditionResult
	{
		
		private int _ID;
		
		private string _linkimg;
		
		private System.DateTime _CreateDate;
		
		private System.Nullable<bool> _IsDownLoaded;
		
		private string _Domain;
		
		private string _Counter;
		
		private string _GroupName;
		
		private string _Category;
		
		private System.Nullable<bool> _IsBadURL;
		
		private System.Nullable<bool> _IsCheckLive;
		
		private System.Nullable<int> _HotLevel;
		
		private System.Nullable<bool> _IsNice;
		
		public GetRandomImageByConditionResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_linkimg", DbType="NVarChar(2500) NOT NULL", CanBeNull=false)]
		public string linkimg
		{
			get
			{
				return this._linkimg;
			}
			set
			{
				if ((this._linkimg != value))
				{
					this._linkimg = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime NOT NULL")]
		public System.DateTime CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this._CreateDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDownLoaded", DbType="Bit")]
		public System.Nullable<bool> IsDownLoaded
		{
			get
			{
				return this._IsDownLoaded;
			}
			set
			{
				if ((this._IsDownLoaded != value))
				{
					this._IsDownLoaded = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Domain", DbType="NVarChar(1000)")]
		public string Domain
		{
			get
			{
				return this._Domain;
			}
			set
			{
				if ((this._Domain != value))
				{
					this._Domain = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Counter", DbType="NVarChar(500)")]
		public string Counter
		{
			get
			{
				return this._Counter;
			}
			set
			{
				if ((this._Counter != value))
				{
					this._Counter = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupName", DbType="NVarChar(1000)")]
		public string GroupName
		{
			get
			{
				return this._GroupName;
			}
			set
			{
				if ((this._GroupName != value))
				{
					this._GroupName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category", DbType="NVarChar(1000)")]
		public string Category
		{
			get
			{
				return this._Category;
			}
			set
			{
				if ((this._Category != value))
				{
					this._Category = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsBadURL", DbType="Bit")]
		public System.Nullable<bool> IsBadURL
		{
			get
			{
				return this._IsBadURL;
			}
			set
			{
				if ((this._IsBadURL != value))
				{
					this._IsBadURL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsCheckLive", DbType="Bit")]
		public System.Nullable<bool> IsCheckLive
		{
			get
			{
				return this._IsCheckLive;
			}
			set
			{
				if ((this._IsCheckLive != value))
				{
					this._IsCheckLive = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HotLevel", DbType="Int")]
		public System.Nullable<int> HotLevel
		{
			get
			{
				return this._HotLevel;
			}
			set
			{
				if ((this._HotLevel != value))
				{
					this._HotLevel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsNice", DbType="Bit")]
		public System.Nullable<bool> IsNice
		{
			get
			{
				return this._IsNice;
			}
			set
			{
				if ((this._IsNice != value))
				{
					this._IsNice = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
